name = "value-creator"
type = "javascript"

zone_id = "6fd2410ed341d69e3d27428d0721b3fd"
account_id = "d51538ef32047368c4a3eb549f5e7f8a"
route = "*create-value.xyz/*"
workers_dev = true
compatibility_date = "2022-01-17"

kv_namespaces = [
	 { binding = "SESSIONS", id = "ef87ae409c954f38bebf2a23e1fda8ab" },
	 { binding = "VALUES", id= "2eb1ef9c49a5454a887a6fcb152d6e69" }
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"

[vars]
SESSION_SECRET="secret"
